import { GlobalProvider } from "@/features/provider/global.provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
